import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { SignIn } from 'components';
import styles from '../styles/Home.module.css';
import { trpc } from 'src/trpc';
import { useEffect } from 'react';

const Home: NextPage = () => {
  // --- Server Auth flow ---
  // 1. Check that user is authenticated (that there is session or sessionId cookie)
  // 2. If user is not authenticated then show login components
  // 3. If user is authenticated dont show login components

  // --- Client Auth flow ---
  // 1. Get session if there isn't (make the request on client side to the api)
  // 2. If there is an authenticated user dont show login UI
  // 3. If there isn't an authenticated user show login UI

  /**
   * --- NOTE ---
   * The Next.js's logic that includes getServerSideProps or getStaticProps
   * and client side is handle by tRPC and React-Query
   */
  const { data: session } = trpc.useQuery(['session:getSession']);

  const { userId, csrfToken } = session || {};

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          {userId ? (
            <p>
              Welcome <span>{userId}</span>
            </p>
          ) : (
            <SignIn />
          )}
        </div>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
