services:
  movie-polls-db:
    image: mysql:latest
    restart: always
    volumes: 
      - ./mysql-data:/var/lib/mysql
      - ./database-scripts/init-database.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  movie-polls-cache:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis-server:/usr/local/etc/redis
